channels:
  - conda-forge

dependencies:
  - python=3.7.3
  # https://www.anaconda.com/utilizing-the-new-compilers-in-anaconda-distribution-5/
  - c-compiler=1.0.4
  - cmake=3.14.0
  - qt=5.12.5  # conda-forge does not have 5.13.2 available
  - pip
  - pip:
    - numpy==1.17.2
    - gym==0.15.3
    - filelock==3.0.10
    - cffi==1.13.2
    - pyglet==1.3.2
    - imageio==2.6.1
    - imageio-ffmpeg==0.3.0